services:
  php:
    container_name: php_financas
    build:
      context: .
      dockerfile: ./devops/docker/php/Dockerfile
    volumes:
      - .:/var/www/html/controle-gastos-service:rw
    networks:
      - external-net
    extra_hosts:
      - auth-service:host-gateway

  apache2:
    container_name: apache_financas
    build:
      context: .
      dockerfile: ./devops/docker/apache/Dockerfile
    ports:
      - 3030:80
    volumes:
      - .:/var/www/html/controle-gastos-service:rw
      - ./devops/docker/apache/vhosts/api.conf:/etc/apache2/sites-enabled/default.conf
    networks:
      - external-net
    depends_on:
      - php
#  db:
#    container_name: postgres
#    build:
#      context: .
#      dockerfile: ./devops/docker/postgres/Dockerfile
##    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - .:/var/lib/postegresql/data:rw
#      - ./devops/docker/postgres/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql
#    networks:
#      external-net:

networks:
  external-net:
    external:
      name: external-net