services:
  php_financa:
    container_name: php_financas
    build:
      context: .
      dockerfile: ./devops/docker/php/Dockerfile
    volumes:
      - .:/var/www/html/controle-gastos-service:rw
      - /certificates:/certificates
      - ./devops/docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - external-net
    extra_hosts:
      - auth-service:host-gateway
      - redis:host-gateway

  apache2_financa:
    container_name: apache_financas
    build:
      context: .
      dockerfile: ./devops/docker/apache/Dockerfile
    ports:
      - 3030:80
    volumes:
      - .:/var/www/html/controle-gastos-service:rw
      - ./devops/docker/apache/vhosts/api.conf:/etc/apache2/sites-enabled/default.conf
    networks:
      - external-net
    depends_on:
      - php_financa

  db_financa:
    container_name: postgres_financas
    image: postgres:latest
    environment:
      POSTGRES_DB: 'financa'
      POSTGRES_USER: 'user_financa'
      POSTGRES_PASSWORD: 'financas'
    ports:
      - 5433:5432
    volumes:
      - .:/var/lib/postegresql/data:rw
      - ./devops/docker/postgres/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql
    networks:
      external-net:

networks:
  external-net:
    external: true